services:
  wagashiapp-dev-mysql:
    container_name: "wagashiapp.dev.db.mysql"
    platform: linux/amd64
    image: mysql:8.4
    networks:
      - wagashiapp-dev-network
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./db/data:/var/lib/mysql

  wagashiapp-dev-myadmin:
    container_name: "wagashiapp.dev.myadmin"
    depends_on:
      - wagashiapp-dev-mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: wagashiapp-dev-mysql
    restart: always
    ports:
      - "10001:80"
    networks:
      - wagashiapp-dev-network

networks:
  wagashiapp-dev-network:
    external: true
