services:
  wagashiapp-dev-admin-web:
    container_name: "wagashiapp.dev.admin.web"
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "10011:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wagashiapp-dev-admin-php
    networks:
      - wagashiapp-dev-network

  wagashiapp-dev-admin-php:
    container_name: "wagashiapp.dev.admin.php"
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - wagashiapp-dev-network

  util-npm:
    image: node:20.10.0
    working_dir: /var/www/html
    #entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html

networks:
  wagashiapp-dev-network:
    external: true
